name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- name: Setup .NET Core
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 3.1.301
    - name: Setup NetCore
      run: |
           wget https://dot.net/v1/dotnet-install.sh
           chmod +x ./dotnet-install.sh
           ./dotnet-install.sh
           export PATH=~/.dotnet:$PATH
    #- name: Install dependencies
    #  run: dotnet restore
    #- name: Build
    #  run: dotnet build --configuration Release --no-restore
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish -c Release /p:PublishReadyToRun=true /p:PublishTrimmed=true -o public
    - name: checks
      run: |
          pwd;find . | sort | sed '1d;s/^\.//;s/\/\([^/]*\)$/|--\1/;s/\/[^/|]*/|  /g'
          ls
          ls /home/runner
    #- uses: actions/setup-node@v2-beta
    #  with:
    #    node-version: '12'
    #- name: Deploy to netlify
      #uses: netlify/actions/cli@master
      #env:
      #  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #with:
      #  args: deploy --dir=/home/runner/work/ScenarioViewWEB/ScenarioViewWEB/publish/wwwroot --prod
      #  secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
